routes/admin.php
<?php

use App\Http\Controllers\Admin\CommentController;
use App\Http\Controllers\Admin\MediaLibraryController;
use App\Http\Controllers\Admin\PostController;
use App\Http\Controllers\Admin\PostThumbnailController;
use App\Http\Controllers\Admin\ShowDashboard;
use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Route;

Route::get('dashboard', ShowDashboard::class)->name('dashboard');
Route::resource('posts', PostController::class);
Route::delete('/posts/{post}/thumbnail', [PostThumbnailController::class, 'destroy'])->name('posts_thumbnail.destroy');
Route::resource('users', UserController::class)->only(['index', 'edit', 'update']);
Route::resource('comments', CommentController::class)->only(['index', 'edit', 'update', 'destroy']);
Route::resource('media', MediaLibraryController::class)->only(['index', 'show', 'create', 'store', 'destroy']);

routes/web.php
<?php

use App\Http\Controllers\NewsletterSubscriptionController;
use App\Http\Controllers\PostCommentController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\PostFeedController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [PostController::class, 'index'])->name('home');
Route::get('/posts/feed', [PostFeedController::class, 'index'])->name('posts.feed');
Route::resource('posts', PostController::class)->only('show');
Route::resource('users', UserController::class)->only('show');
Route::resource('posts.comments', PostCommentController::class)->only('index');

Route::get('newsletter-subscriptions/unsubscribe', [NewsletterSubscriptionController::class, 'unsubscribe'])->name('newsletter-subscriptions.unsubscribe');

app/Models/Media.php
<?php

namespace App\Models;

use Spatie\MediaLibrary\MediaCollections\Models\Media as BaseMedia;

class Media extends BaseMedia
{
    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $casts = [
        'posted_at' => 'datetime',
        'manipulations' => 'array',
        'custom_properties' => 'array',
        'generated_conversions' => 'array',
        'responsive_images' => 'array',
    ];
}

app/Http/Controllers/Api/V1/MediaController.php
<?php

namespace App\Http\Controllers\Api\V1;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\MediaLibraryRequest;
use App\Http\Resources\Media as MediaResource;
use App\Models\Media;
use App\Models\MediaLibrary;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\ResourceCollection;
use Illuminate\Http\Response;

class MediaController extends Controller
{
    /**
     * Return the comments.
     */
    public function index(Request $request): ResourceCollection
    {
        return MediaResource::collection(
            MediaLibrary::first()->media()->paginate($request->input('limit', 20))
        );
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(MediaLibraryRequest $request): MediaResource
    {
        $this->authorize('store', Media::class);

        $image = $request->file('image');
        $name = $image->getClientOriginalName();

        if ($request->filled('name')) {
            $name = $request->input('name');
        }

        return new MediaResource(
            MediaLibrary::first()
                ->addMedia($image)
                ->usingName($name)
                ->toMediaCollection()
        );
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Media $medium): Response
    {
        $this->authorize('delete', $medium);

        $medium->delete();

        return response()->noContent();
    }
}

resources/views/admin/media/_list.blade.php
<table class="table table-striped table-sm table-responsive-md">
    <caption>{{ trans_choice('media.count', $media->count()) }}</caption>
    <thead>
        <tr>
            <th>@lang('media.attributes.image')</th>
            <th>@lang('media.attributes.name')</th>
            <th>@lang('media.attributes.url')</th>
            <th>@lang('media.attributes.posted_at')</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach($media as $medium)
            <tr>
                <td>
                    <a href="{{ $medium->getUrl() }}" target="_blank">
                        <img src="{{ $medium->getUrl('thumb') }}" alt="{{ $medium->name }}" width="100">
                    </a>
                </td>
                <td>{{ $medium->name }}</td>
                <td>
                    <div class="input-group">
                        <input
                            id="@domid($medium)"
                            type="text"
                            class="form-control"
                            readonly
                            value="{{ url($medium->getUrl()) }}"
                        >

                        <button class="input-group-text btn" data-clipboard-target="#@domid($medium)">
                            <x-icon name="clipboard" prefix="fa-regular" />
                        </button>
                    </div>
                </td>
                <td>@humanize_date($medium->posted_at, 'd/m/Y H:i:s')</td>
                <td>
                    <a href="{{ $medium->getUrl() }}" title="@lang('media.show')" class="btn btn-primary btn-sm" target="_blank">
                        <x-icon name="eye" prefix="fa-regular" />
                    </a>

                    <a href="{{ route('admin.media.show', $medium) }}" title="@lang('media.download')" class="btn btn-primary btn-sm">
                        <x-icon name="download" />
                    </a>

                    <form action="{{ route('admin.media.destroy', $medium) }}" method="POST" class="form-inline" data-confirm="@lang('forms.media.delete')">
                        @method('DELETE')
                        @csrf

                        <button type="submit" name="submit" class="btn btn-outline-danger btn-sm" title="@lang('media.delete')">
                            <x-icon name="trash" />
                        </button>
                    </form>
                </td>
            </tr>
        @endforeach
    </tbody>
</table>

resources/views/admin/media/create.blade.php
@extends('admin.layouts.app')

@section('content')
    <h1>@lang('media.create')</h1>

    <form action="{{ route('admin.media.store') }}" method="POST" enctype="multipart/form-data">
        @csrf

        <div class="form-group mb-3">
            <label class="form-label" for="image">
                @lang('media.attributes.image')
            </label>

            <input
                type="file"
                name="image"
                id="image"
                accept="image/*"
                @class(['form-control', 'is-invalid' => $errors->has('image')])
                required
            >

            @error('image')
                <span class="invalid-feedback">{{ $message }}</span>
            @enderror
        </div>

        <div class="form-group mb-3">
            <label class="form-label" for="name">
                @lang('media.attributes.name')
            </label>

            <input
                type="text"
                id="name"
                name="name"
                @class(['form-control', 'is-invalid' => $errors->has('name')])
                value="{{ old('name') }}"
            >

            @error('name')
                <span class="invalid-feedback">{{ $message }}</span>
            @enderror
        </div>


        <a href="{{ route('admin.media.index') }}" class="btn btn-light">
            <x-icon name="chevron-left" />

            @lang('forms.actions.back')
        </a>

        <button type="submit" class="btn btn-primary">
            <x-icon name="save" />

            @lang('forms.actions.save')
        </button>
    </form>
@endsection

resources/views/admin/media/index.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="page-header d-flex justify-content-between">
      <h1>@lang('dashboard.media')</h1>

      <a href="{{ route('admin.media.create') }}" class="btn btn-primary btn-sm align-self-center">
        <x-icon name="plus-square" prefix="fa-regular" />

        @lang('forms.actions.add')
      </a>
    </div>

    @include('admin/media/_list')
@endsection