routes/admin.php
<?php

use App\Http\Controllers\Admin\CommentController;
use App\Http\Controllers\Admin\MediaLibraryController;
use App\Http\Controllers\Admin\PostController;
use App\Http\Controllers\Admin\PostThumbnailController;
use App\Http\Controllers\Admin\ShowDashboard;
use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Route;

Route::get('dashboard', ShowDashboard::class)->name('dashboard');
Route::resource('posts', PostController::class);
Route::delete('/posts/{post}/thumbnail', [PostThumbnailController::class, 'destroy'])->name('posts_thumbnail.destroy');
Route::resource('users', UserController::class)->only(['index', 'edit', 'update']);
Route::resource('comments', CommentController::class)->only(['index', 'edit', 'update', 'destroy']);
Route::resource('media', MediaLibraryController::class)->only(['index', 'show', 'create', 'store', 'destroy']);

routes/web.php
<?php

use App\Http\Controllers\NewsletterSubscriptionController;
use App\Http\Controllers\PostCommentController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\PostFeedController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [PostController::class, 'index'])->name('home');
Route::get('/posts/feed', [PostFeedController::class, 'index'])->name('posts.feed');
Route::resource('posts', PostController::class)->only('show');
Route::resource('users', UserController::class)->only('show');
Route::resource('posts.comments', PostCommentController::class)->only('index');

Route::get('newsletter-subscriptions/unsubscribe', [NewsletterSubscriptionController::class, 'unsubscribe'])->name('newsletter-subscriptions.unsubscribe');

app/Models/Comment.php
<?php

namespace App\Models;

use App\Concern\Likeable;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Comment extends Model
{
    use HasFactory, Likeable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'author_id',
        'post_id',
        'content',
        'posted_at'
    ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $casts = [
        'posted_at' => 'datetime'
    ];

    /**
     * Scope a query to only include comments posted last week.
     */
    public function scopeLastWeek(Builder $query): Builder
    {
        return $query->whereBetween('posted_at', [carbon('1 week ago'), now()])
            ->latest();
    }

    /**
     * Scope a query to order comments by latest posted.
     */
    public function scopeLatest(Builder $query): Builder
    {
        return $query->orderBy('posted_at', 'desc');
    }

    /**
     * Return the comment's author
     */
    public function author(): BelongsTo
    {
        return $this->belongsTo(User::class, 'author_id');
    }

    /**
     * Return the comment's post
     */
    public function post(): BelongsTo
    {
        return $this->belongsTo(Post::class);
    }
}

app/Http/Controllers/Admin/CommentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\CommentsRequest;
use App\Models\Comment;
use App\Models\User;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;

class CommentController extends Controller
{
    /**
     * Show the application comments index.
     */
    public function index(): View
    {
        return view('admin.comments.index', [
            'comments' => Comment::with('post', 'author')->latest()->paginate(50)
        ]);
    }

    /**
     * Display the specified resource edit form.
     */
    public function edit(Comment $comment): View
    {
        return view('admin.comments.edit', [
            'comment' => $comment,
            'users' => User::pluck('name', 'id')
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(CommentsRequest $request, Comment $comment): RedirectResponse
    {
        $comment->update($request->validated());

        return redirect()->route('admin.comments.edit', $comment)->withSuccess(__('comments.updated'));
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Comment $comment): RedirectResponse
    {
        $comment->delete();

        return redirect()->route('admin.comments.index')->withSuccess(__('comments.deleted'));
    }
}

app/Http/Controllers/Api/V1/CommentController.php
<?php

namespace App\Http\Controllers\Api\V1;

use App\Http\Controllers\Controller;
use App\Http\Resources\Comment as CommentResource;
use App\Models\Comment;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\ResourceCollection;
use Illuminate\Http\Response;

class CommentController extends Controller
{
    /**
     * Return the comments.
     */
    public function index(Request $request): ResourceCollection
    {
        return CommentResource::collection(
            Comment::latest()->paginate($request->input('limit', 20))
        );
    }

    /**
     * Return the specified resource.
     */
    public function show(Comment $comment): CommentResource
    {
        return new CommentResource($comment);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Comment $comment): Response
    {
        $this->authorize('delete', $comment);

        $comment->delete();

        return response()->noContent();
    }
}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CommentsRequest;
use App\Models\Comment;
use Illuminate\Support\Facades\Auth;
use Tonysm\TurboLaravel\Http\MultiplePendingTurboStreamResponse;

class CommentController extends Controller
{
    /**
     * Store a newly created resource in storage.
     */
    public function store(CommentsRequest $request): MultiplePendingTurboStreamResponse
    {
        $comment = Auth::user()->comments()->create($request->validated());

        return response()->turboStream([
            response()->turboStream()->prepend('comments')->view('comments._comment', ['comment' => $comment]),
            response()->turboStream()->replace('comments_form')->view('comments._form', ['post' => $comment->post]),
            response()->turboStream()
            ->update('comments_count', trans_choice('comments.count', $comment->post->comments()->count()))
        ]);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Comment $comment): MultiplePendingTurboStreamResponse
    {
        $this->authorize('delete', $comment);

        $comment->delete();

        return response()->turboStream([
            response()->turboStream()->remove($comment),
            response()->turboStream()
            ->update('comments_count', trans_choice('comments.count', $comment->post->comments()->count()))
        ]);
    }
}

resources/views/comments/_comment.blade.php
<x-card :id="dom_id($comment)" class="mb-3">
  <div class="card-title d-flex justify-content-between">
    <p class="card-text mb-0">
      <small class="text-muted">@humanize_date($comment->posted_at)</small>
    </p>

    @can('delete', $comment)
      <form action="{{ route('comments.destroy', $comment) }}" method="POST" class="form-inline" data-turbo="true" data-turbo-confirm="@lang('forms.comments.delete')">
        @method('DELETE')
        @csrf

        <button type="submit" class="btn-close"></button>
      </form>
    @endcan
  </div>

  <h6>
    <a href="{{ route('users.show', $comment->author) }}">
      {{ $comment->author->name }}
    </a>
  </h6>

  <p class="card-text">
    {{ $comment->content }}
  </p>
</x-card>

resources/views/comments/_form.blade.php
@auth
  <form id="comments_form" action="{{ route('comments.store') }}" method="POST" data-turbo="true">
    @csrf

    <input type="hidden" name="post_id" value="{{ $post->id }}">

    <div class="form-group mb-3">
      <textarea
          name="content"
          id="content"
          cols="50"
          rows="3"
          @class(['form-control', 'is-invalid' => $errors->has('content')])
          placeholder="@lang('comments.placeholder.content')"
          required
      >{{ old('content', $comment ?? null) }}</textarea>

      @error('content')
        <span class="invalid-feedback">{{ $message }}</span>
      @enderror
    </div>

    <div class="form-group mb-3 text-end">
      <button type="submit" class="btn btn-primary">
          <x-icon name="paper-plane" />

          @lang('comments.comment')
      </button>
    </div>
  </form>
@else
  <x-alert type="warning">
    @lang('comments.sign_in_to_comment')
  </x-alert>
@endauth

resources/views/comments/_list.blade.php
<h2 id="comments_count" class="mt-2">
    {{ trans_choice('comments.count', $post->comments_count) }}
</h2>

<x-turbo-frame id="comments" :src="route('posts.comments.index', $post)" loading="lazy">
    <x-alert type="info">
        <x-icon name="spinner" class="fa-spin" />

        @lang('comments.loading_comments')
    </x-alert>
</x-turbo-frame>

@include ('comments/_form')

resources/views/comments/index.blade.php
<x-turbo-frame id="comments">
    @each('comments/_comment', $comments, 'comment')
</x-turbo-frame>